version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/ddookddackapp
    overwrite: yes
permissions:
  - object: /home/ubuntu/ddookddackapp
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 1000
      runas: root